import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {ClerkProvider} from "@clerk/nextjs";
import {Navbar} from "~/app/_components/navbar";
import {NextSSRPlugin} from "@uploadthing/react/next-ssr-plugin";
import {extractRouterConfig} from "uploadthing/server";
import {ourFileRouter} from "~/app/api/uploadthing/core";

export const metadata: Metadata = {
  title: "Next Gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
  modal
}: Readonly<{
    children: React.ReactNode
    modal: React.ReactNode
}>) {
  return (
      <ClerkProvider>
        <html lang="en" className={`${GeistSans.variable}`}>
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}/>
              <body className='flex flex-col gap-4'>
                <Navbar/>
                    {children}
                    {modal}
                <div id='modal-root'/>
              </body>
        </html>
      </ClerkProvider>
  );
}
